{
 "title": "1. Homelab",
 "tags": [ "Homelab" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Synology RAID Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "raidStatus{job=\"snmp\", raidName=~\"Volume.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consul tolerance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(consul_autopilot_failure_tolerance{})\n"
    }
   ]
  },
  {
   "title": "Nomad tolerance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nomad_nomad_autopilot_failure_tolerance{job=\"nomad\"}",
     "legendFormat": "fault tolerance"
    }
   ]
  },
  {
   "title": "Nomad clients - Resources allocated",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "100 -\nnomad_client_unallocated_cpu{}\n/\n(nomad_client_allocated_cpu{}\n+ nomad_client_unallocated_cpu{}) * 100",
     "legendFormat": "cpu utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_memory{}\n/\n(nomad_client_allocated_memory{}\n+ nomad_client_unallocated_memory{}) * 100",
     "legendFormat": "memory utilization"
    },
    {
     "expr": "100 -\nnomad_client_unallocated_disk{}\n/\n(nomad_client_allocated_disk{}\n+ nomad_client_unallocated_disk{}) * 100",
     "legendFormat": "disk utilization"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"storage.home\"} - node_memory_MemFree_bytes{instance=\"storage.home\"} - (node_memory_Cached_bytes{instance=\"storage.home\"} + node_memory_Buffers_bytes{instance=\"storage.home\"} + node_memory_SReclaimable_bytes{instance=\"storage.home\"})) / node_memory_MemTotal_bytes{instance=\"storage.home\"} * 100",
     "legendFormat": "Storage"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"master.home\"} - node_memory_MemFree_bytes{instance=\"master.home\"} - (node_memory_Cached_bytes{instance=\"master.home\"} + node_memory_Buffers_bytes{instance=\"master.home\"} + node_memory_SReclaimable_bytes{instance=\"master.home\"})) / node_memory_MemTotal_bytes{instance=\"master.home\"} * 100",
     "legendFormat": "Master"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"compute1.home\"} - node_memory_MemFree_bytes{instance=\"compute1.home\"} - (node_memory_Cached_bytes{instance=\"compute1.home\"} + node_memory_Buffers_bytes{instance=\"compute1.home\"} + node_memory_SReclaimable_bytes{instance=\"compute1.home\"})) / node_memory_MemTotal_bytes{instance=\"compute1.home\"} * 100",
     "legendFormat": "Compute1"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"compute2.home\"} - node_memory_MemFree_bytes{instance=\"compute2.home\"} - (node_memory_Cached_bytes{instance=\"compute2.home\"} + node_memory_Buffers_bytes{instance=\"compute2.home\"} + node_memory_SReclaimable_bytes{instance=\"compute2.home\"})) / node_memory_MemTotal_bytes{instance=\"compute2.home\"} * 100",
     "legendFormat": "Compute2"
    },
    {
     "expr": "(node_memory_MemTotal_bytes{instance=\"unifi.home\"} - node_memory_MemFree_bytes{instance=\"unifi.home\"} - (node_memory_Cached_bytes{instance=\"unifi.home\"} + node_memory_Buffers_bytes{instance=\"unifi.home\"} + node_memory_SReclaimable_bytes{instance=\"unifi.home\"})) / node_memory_MemTotal_bytes{instance=\"unifi.home\"} * 100",
     "legendFormat": "UDM"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"storage.home\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"storage.home\"}[$__rate_interval]))",
     "legendFormat": "Storage"
    },
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"master.home\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"master.home\"}[$__rate_interval]))",
     "legendFormat": "Master"
    },
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"compute1.home\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"compute1.home\"}[$__rate_interval]))",
     "legendFormat": "Compute1"
    },
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"compute2.home\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"compute2.home\"}[$__rate_interval]))",
     "legendFormat": "Compute2"
    },
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"unifi.home\", mode!=\"idle\"}[$__rate_interval])) * 100) / on(instance) sum by(instance) (irate(node_cpu_seconds_total{instance=\"unifi.home\"}[$__rate_interval])) ",
     "legendFormat": "UDM"
    }
   ]
  },
  {
   "title": "Storage Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp\",raidName=\"Volume 1\"}*raidFreeSize{job=\"snmp\",raidName=\"Volume 1\"})",
     "legendFormat": "NAS HDD Volume"
    },
    {
     "expr": "100-(100/raidTotalSize{job=\"snmp\",raidName=\"Volume 2\"}*raidFreeSize{job=\"snmp\",raidName=\"Volume 2\"})",
     "legendFormat": "NAS NVMe Volume"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"compute1.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"compute1.home\",mountpoint=\"/\"})",
     "legendFormat": "Compute1"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"compute2.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"compute2.home\",mountpoint=\"/\"})",
     "legendFormat": "Compute2"
    },
    {
     "expr": "100*(1 - node_filesystem_avail_bytes{instance=\"master.home\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=\"master.home\",mountpoint=\"/\"})",
     "legendFormat": "Master"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"storage.home\", device=\"dm-3\"}[$__rate_interval])",
     "legendFormat": "NAS SATA volume"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"storage.home\", device=\"dm-1\"}[$__rate_interval])",
     "legendFormat": "NAS NVMe volume"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"compute1.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Compute1"
    },
    {
     "expr": "irate(node_disk_io_time_seconds_total{instance=\"compute2.home\",device=\"sda\"}[$__rate_interval])",
     "legendFormat": "Compute2"
    }
   ]
  },
  { "title": "Nomad Allocations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Allocations",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "nomad_client_allocations_blocked{}",
     "legendFormat": "blocked"
    },
    {
     "expr": "nomad_client_allocations_migrating{}",
     "legendFormat": "migrating"
    },
    {
     "expr": "nomad_client_allocations_pending{}",
     "legendFormat": "pending"
    },
    {
     "expr": "nomad_client_allocations_running{}",
     "legendFormat": "running"
    },
    {
     "expr": "nomad_client_allocations_start{}",
     "legendFormat": "start"
    },
    {
     "expr": "nomad_client_allocations_terminal{}",
     "legendFormat": "terminal"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nomad_client_allocs_cpu_total_percent{job=\"nomad\"}",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }} - {{ instance }} - {{ alloc_id }}"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(nomad_client_allocs_memory_usage{job=\"nomad\"}\n- \nnomad_client_allocs_memory_cache{job=\"nomad\"})\n/\nnomad_client_allocs_memory_allocated{job=\"nomad\"} * 100",
     "legendFormat": "{{ exported_job }} - {{ task_group }} - {{ task }} - {{ instance }} - {{ alloc_id }}"
    }
   ]
  },
  { "title": "SDN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Upstream request time : heatmap",
   "type": "heatmap",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/configuration/upstream/cluster_manager/cluster_stats",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_external_upstream_rq_time_bucket{}[$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Connection request bytes",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#arch-overview-outlier-detection",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_tx_bytes_total{consul_destination_service!=\"\"} [$__rate_interval:])",
     "legendFormat": "{{consul_source_service}} → {{consul_destination_service}}"
    },
    {
     "expr": "irate(traefik_service_requests_bytes_total{} [$__rate_interval:])",
     "legendFormat": "traefik → {{service}}"
    }
   ]
  },
  {
   "title": "Connection response bytes",
   "type": "timeseries",
   "description": "https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/outlier#arch-overview-outlier-detection",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(envoy_cluster_upstream_cx_rx_bytes_total{consul_destination_service!=\"\"} [$__rate_interval:])",
     "legendFormat": "{{consul_destination_service}} → {{consul_source_service}}"
    },
    {
     "expr": "irate(traefik_service_responses_bytes_total{} [$__rate_interval:])",
     "legendFormat": "{{service}} → traefik"
    }
   ]
  }
 ]
}